# examples/example_4/config.yaml
experiment_type: experiments.linear_function.logic.LinearFunctionExperiment
experiment_description: "Generates data from a linear function y = mx + c."
n_points: 100
m: 2.0
c: 5.0
x_min: 0.0
x_max: 10.0