# examples/parameter_sweep_example/config_base.yaml
experiment_type: experiments.predator_prey.logic.PredatorPreyExperiment
experiment_description: "Base configuration for Predator-Prey parameter sweep."
n_steps: 70  # Note:  We're using a fixed n_steps here.
initial_prey: 150
initial_predators: 5
# prey_growth_rate:  # These will be defined by the parameter sweep
# prey_death_rate:   # These will be defined by the parameter sweep
predator_growth_rate: 0.001
predator_death_rate: 0.185
save_csv: True  # Enable CSV output
static_plot_format: 'svg' # Example: Generate SVG plots