# examples/config.yaml
experiment_type: experiments.example_experiment.logic.ExampleExperiment
experiment_description: "A simple simulation of a sine wave."  # Add this line
n_steps: 100
amplitude: 2.5