# examples/example_6/config.yaml
experiment_type: experiments.predator_prey_calibration.logic.PredatorPreyCalibrationExperiment
experiment_description: "Calibration of the Predator-Prey model using observed data."
n_steps: 350  # Simulate for a longer time
initial_prey: 100  # Initial values - these might be adjusted
initial_predators: 18 # Initial values
prey_growth_rate: 0.25 # Initial parameter values - these will be adjusted
prey_death_rate: 0.004
predator_growth_rate: 0.002
predator_death_rate: 0.085
observed_data_path: "examples/example_6/observed_data.csv"  # Path to observed data